name: CI linting

on:
  pull_request:
    branches: ['main']

jobs:
  ci_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8 + pyproject plugin
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-pyproject

      - name: Run flake8
        run: |
          flake8 agent_baselines/ tests/
