name: CI_tests

on:
  pull_request:
    branches: ['main']

jobs:
  ci_test:
    runs-on: ubuntu-latest
    env:
      IS_CI: true
      OPENAI_API_KEY: "Fake key, but the var needs to be set or else Inspect will complain at import time"
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx for caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image with layer caching
      - name: Build main Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          tags: agent-baselines:latest
          target: agent-baselines-base
          cache-from: type=gha,scope=agent-baselines  # Use GitHub Actions cache
          cache-to: type=gha,mode=max,scope=agent-baselines
          load: true  # Make the image available for later steps

      - name: Run tests
        run: |
          # Generate '-e VAR' for all env vars except '_*'
          ENV_ARGS=$(env | grep -vE '^_' | awk '{print "-e " $1}')
          make test
